name: Auto-Update MMDB

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download GeoLite2 ASN Database
        run: |
          wget -O database.tar.gz "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-ASN&license_key=${{ secrets.MAXMIND_KEY }}&suffix=tar.gz"
          tar -xzf database.tar.gz --strip-components=1 --wildcards '*.mmdb'
          rm database.tar.gz

      - name: Commit and Push to GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add GeoLite2-ASN.mmdb
          # The next line prevents failure if the file hasn't changed
          git commit -m "Automated MMDB Update" || echo "No changes to commit"
          git push
